name: Events Demo 1
on: 
  pull_request:
    types: 
      - opened
    branches:
      - master # master
      - 'dev-*' # dew-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button    
  workflow_dispatch:
  push:
    branches:
      - master # master
      - 'dev-*' # dew-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button  
    paths-ignore:
      - '.github/workflows/*' # above push event wont trigger if we change anything in this path file
jobs:
  deploy:
    runs-on: macos-13
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."